### ISSUE TITLE
Configure angular2-locker with karma, WARN: 404: /base/angular2-locker.js

### ISSUE THREAD

**Issue by ghudeihed** [MikaAK/angular2-locker#8] opened 2016-06-13 02:40 UTC
I am getting a 404 error when running tests 
![image](https://cloud.githubusercontent.com/assets/169615/15995761/ffdcaa36-30d4-11e6-866d-1a4d91461bbc.png)

I added the module path to the files array in karma.conf.js, but now I am getting different error

files: [
      // Polyfills.
      'node_modules/core-js/client/shim.min.js',

      // System.js for module loading
      'node_modules/systemjs/dist/system-polyfills.js',
      'node_modules/systemjs/dist/system.src.js',

      // Zone.js dependencies
      'node_modules/zone.js/dist/zone.js',
      'node_modules/zone.js/dist/jasmine-patch.js',
      'node_modules/zone.js/dist/async-test.js',
      'node_modules/zone.js/dist/fake-async-test.js',

      // RxJs.
      { pattern: 'node_modules/rxjs/**/*.js', included: false, watched: false },
      { pattern: 'node_modules/rxjs/**/*.js.map', included: false, watched: false },

      // paths loaded via module imports
      // Angular itself
      { pattern: 'node_modules/@angular/**/*.js', included: false, watched: true },

      { pattern: 'dist/dev/**/*.js', included: false, watched: true },
      { pattern: 'dist/dev/**/*.html', included: false, watched: true, served: true },
      { pattern: 'dist/dev/**/*.css', included: false, watched: true, served: true },
      { pattern: 'node_modules/systemjs/dist/system-polyfills.js', included: false, watched: false }, // PhantomJS2 (and possibly others) might require it
      
      'node_modules/angular2-locker/dist/*.js',

      // suppress annoying 404 warnings for resources, images, etc.
      { pattern: 'dist/dev/assets/**/*', watched: false, included: false, served: true },

      'test-main.js'
    ],

![image](https://cloud.githubusercontent.com/assets/169615/15995679/e91e4d3c-30d3-11e6-81bf-ba8135467e59.png)

**Comment by MikaAK** [comment] 2016-06-13 17:32
It actually works as it is right now. 
<img width="716" alt="screen shot 2016-06-13 at 10 29 49 am" src="https://cloud.githubusercontent.com/assets/4650931/16016856/dce84bb6-3151-11e6-8c89-aaeb8f3e402a.png"> the fact that it shows 0 tests running on yours is concerning as well. The needed files are loaded in from the [karma-shim](https://github.com/MikaAK/angular2-locker/blob/master/karma-shim.js)

**Comment by ghudeihed** [comment] 2016-06-14 20:19
@MikaAK thanks a lot, I am going to close this ticket!

**Comment by ghudeihed** [comment] 2016-06-15 18:04
@MikaAK I am still facing the same issue, so I created this repo. with simple settings component that uses a service to get list of settings https://github.com/ghudeihed/angular2-seed-locker

Just by importing Locker it in my test and service, I get the 404 warning and block the rest of the tests from running

**Comment by MikaAK** [comment] 2016-06-18 21:15
Sorry, I'm not sure what the issue is here and I don't have time to go through this and figure it out. You're welcome to create a PR or another issue if you find a solution. Personally, I have tested with angular2-locker and not had a problem with it so I suspect it could be your configuration in some way. I'm gonna close this issue as it seems more of a config problem.

**Closed by MikaAK** 2016-06-18 21:15 UTC
